modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="hudrendererlib"
version="${version}"
displayName="HudRendererLib"
authors="brainage04"
description='''A library for rendering HUD elements.'''

[[dependencies.hudrendererlib]]
modId="neoforge"
type="required"
versionRange="[26.2.0.23-beta,26.3)"
ordering="NONE"
side="CLIENT"

[[dependencies.hudrendererlib]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="CLIENT"

[[dependencies.hudrendererlib]]
modId="cloth_config"
type="required"
versionRange="[26.2.155,)"
ordering="NONE"
side="CLIENT"
