modLoader="javafml"
loaderVersion="[11,)"
license="MIT"
issueTrackerURL="https://github.com/brainage04/HudRendererLib/issues"

[[mods]]
modId="hudrendererlib"
version="${version}"
displayName="HudRendererLib"
iconFile="assets/hudrendererlib/icon.png"
authors="brainage04"
description='''A library for rendering HUD elements.'''
displayURL="https://github.com/brainage04/HudRendererLib"

[[mixins]]
config="hudrendererlib.client.mixins.json"

[[dependencies.hudrendererlib]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.hudrendererlib]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.hudrendererlib]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},)"
ordering="NONE"
side="CLIENT"
