plugins {
	id 'io.github.brainage04.maven-central-publishing' version "${fabricmoddingconventions_version}"
}

mavenCentralPublishing {
	repository.set('brainage04/HudRendererLib')
	publicationName.set(rootProject.mod_name)
	description.set('A library for rendering Heads-Up Display (HUD) elements in NeoForge mods for Minecraft.')
	localRepository.set(rootProject.layout.buildDirectory.dir('local-repo'))
}

dependencies { implementation "me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}" }

tasks.register('javadocJar', Jar) {
	archiveClassifier = 'javadoc'
	from rootProject.file('README.md')
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifactId = "${rootProject.archives_base_name}-neoforge"
			from components.java
			artifact tasks.named('javadocJar')
		}
	}
}
